# Generated by Django 4.1.2 on 2023-01-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdcTables',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_id', models.CharField(max_length=128)),
                ('source_db', models.CharField(blank=True, max_length=128, null=True)),
                ('source_schema', models.CharField(blank=True, max_length=128, null=True)),
                ('source_table', models.CharField(blank=True, max_length=128, null=True)),
                ('target_schema', models.CharField(blank=True, max_length=128, null=True)),
                ('target_table', models.CharField(blank=True, max_length=128, null=True)),
                ('uppercase_fields', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('filter', models.CharField(blank=True, max_length=128, null=True)),
                ('force_init', models.CharField(blank=True, max_length=128, null=True)),
                ('cntrl_fld', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'cdc_tables',
                'managed': True,
                'unique_together': {('id', 'table_id')},
            },
        ),
        migrations.CreateModel(
            name='CdcStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_id', models.CharField(max_length=128)),
                ('last_read_seq', models.CharField(blank=True, max_length=35, null=True)),
                ('init_read_seq', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'cdc_status',
                'managed': True,
                'unique_together': {('id', 'table_id')},
            },
        ),
        migrations.CreateModel(
            name='CdcFields',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_id', models.CharField(max_length=128)),
                ('source_field_name', models.CharField(max_length=128)),
                ('target_field_name', models.CharField(blank=True, max_length=128, null=True)),
                ('field_index', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('field_type', models.CharField(blank=True, max_length=40, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('pk_field', models.DecimalField(blank=True, db_column='pk', decimal_places=0, max_digits=10, null=True)),
                ('required', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'cdc_fields',
                'managed': True,
                'unique_together': {('id', 'table_id', 'source_field_name')},
            },
        ),
        migrations.CreateModel(
            name='CdcConn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conn_type', models.CharField(blank=True, max_length=128, null=True)),
                ('conn_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cdc_conn',
                'managed': True,
                'unique_together': {('id', 'conn_name')},
            },
        ),
    ]
