# Generated by Django 4.1.2 on 2023-01-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial')
    ]

    operations = [
        migrations.AddField(
            model_name='cdcconn',
            name='id',
            field=models.BigAutoField(primary_key=True),
        ),
    ]
