# Generated by Django 4.1.2 on 2023-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230117_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdctables',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='cdcconn',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
