# Generated by Django 4.1.2 on 2023-01-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cdctables_options_alter_cdcconn_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdcconn',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='cdcfields',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='cdcstatus',
            options={'managed': True, 'ordering': ['-id']},
        ),
    ]
